title: Mens Sana
iconURL: assets/default-icon.png
remote_theme: pages-themes/slate@v0.2.0

# for a clean URL
permalink: :slug

social:
  twitter: marcos_calle
  github: MarcusMcFly

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - github-pages
 - jekyll-remote-theme # add this line to the plugins list if you already have one


### comments & analytics
hyvor_talk_website_id: 
google_analytics: G-FQ8VVW0N25

